services:
  legal-status-db:
    image: postgres:18
    networks:
      - hmpps
    container_name: legal-status-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=legal_status
      - POSTGRES_PASSWORD=legal_status
      - POSTGRES_DB=legal_status
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legal_status -d legal_status"]
      interval: 5s
      timeout: 5s
      retries: 10

  hmpps-legal-status-api:
    image: ghcr.io/ministryofjustice/hmpps-legal-status-api:latest
    networks:
      - hmpps
    container_name: hmpps-legal-status-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://legal-status-db:5432/legal_status
    depends_on:
      legal-status-db:
        condition: service_healthy

  hmpps-auth:
    image: ghcr.io/ministryofjustice/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

networks:
  hmpps:
